services:
  triton:
    image: nvcr.io/nvidia/tritonserver:24.08-py3
    command: ["tritonserver", "--model-repository=/models"]
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./model_repository:/models
    shm_size: '2gb'
